# Generated by Django 5.1.1 on 2024-10-20 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_subscriber_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'почта'},
        ),
    ]
