# Generated by Django 5.1.1 on 2024-10-20 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_subscriber_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'почта', 'verbose_name_plural': 'почта'},
        ),
    ]
